### ISSUE TITLE
Add rule

### ISSUE THREAD

**Issue by dopoi16** [fedKotikeD/station-2#7]
I think that it is a good rule for PR:

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

**Comment by dopoi16** [comment]
Oh yes, I forgot. There is some information listed as a comment. I can send it to discord if needed.

**Comment by fedKotikeD** [comment]
Idea is good. I'll think how to add it.
